import uuid

from django.db import models


class MenuItem(models.Model):
    """
    Menu item definitions at org level. Locations can toggle which items
    they sell via LocationMenuItem (or you can start simpler and just
    use is_active globally).
    """

    class Category(models.TextChoices):
        HOT_DRINKS = "hot_drinks", "Hot Drinks"
        COLD_DRINKS = "cold_drinks", "Cold Drinks"
        FOOD = "food", "Food"
        BAKERY = "bakery", "Bakery"
        RETAIL = "retail", "Retail"
        OTHER = "other", "Other"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organisation = models.ForeignKey(
        "core.Organisation", on_delete=models.CASCADE, related_name="menu_items"
    )
    name = models.CharField(max_length=200)
    category = models.CharField(
        max_length=20, choices=Category.choices, default=Category.OTHER
    )
    price = models.DecimalField(max_digits=8, decimal_places=2)
    ingredient_cost = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0,
        help_text="Estimated cost to make this item",
    )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["category", "name"]
        unique_together = ("organisation", "name")

    def __str__(self):
        return f"{self.name} (£{self.price})"

    @property
    def margin(self):
        if self.price > 0:
            return float((self.price - self.ingredient_cost) / self.price * 100)
        return 0


class Sale(models.Model):
    """
    Individual transactions from the POS. These may be imported via CSV,
    API sync, or manual entry. The sales dashboard aggregates this data.
    """

    class PaymentMethod(models.TextChoices):
        CARD = "card", "Card"
        CASH = "cash", "Cash"
        MOBILE = "mobile", "Mobile Payment"
        OTHER = "other", "Other"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    location = models.ForeignKey(
        "core.Location", on_delete=models.CASCADE, related_name="sales"
    )
    transaction_ref = models.CharField(
        max_length=100,
        blank=True,
        help_text="External reference from POS system",
    )
    timestamp = models.DateTimeField(db_index=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(
        max_length=20, choices=PaymentMethod.choices, default=PaymentMethod.CARD
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self):
        return (
            f"Sale £{self.total_amount} @ {self.location.name} "
            f"({self.timestamp:%Y-%m-%d %H:%M})"
        )


class SaleItem(models.Model):
    """Individual line items within a sale."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name="items")
    menu_item = models.ForeignKey(
        MenuItem, on_delete=models.SET_NULL, null=True, related_name="sale_items"
    )
    quantity = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=8, decimal_places=2)
    line_total = models.DecimalField(max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        self.line_total = self.quantity * self.unit_price
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.menu_item.name} × {self.quantity} = £{self.line_total}"


class DailySalesSummary(models.Model):
    """
    Pre-computed daily aggregates for fast dashboard loading.
    Generated by a nightly management command or Celery task.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    location = models.ForeignKey(
        "core.Location", on_delete=models.CASCADE, related_name="daily_summaries"
    )
    date = models.DateField(db_index=True)
    total_revenue = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction_count = models.PositiveIntegerField(default=0)
    average_transaction = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    top_items = models.JSONField(
        default=list,
        blank=True,
        help_text="[{'item_id': ..., 'name': ..., 'qty': ..., 'revenue': ...}, ...]",
    )
    hourly_breakdown = models.JSONField(
        default=dict,
        blank=True,
        help_text="{'07': {'revenue': 120.50, 'transactions': 14}, ...}",
    )
    category_breakdown = models.JSONField(
        default=dict,
        blank=True,
        help_text="{'hot_drinks': {'revenue': ..., 'qty': ...}, ...}",
    )
    waste_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0,
        help_text="Total waste cost for the day",
    )
    waste_percentage = models.FloatField(
        default=0,
        help_text="waste_total / total_revenue × 100",
    )
    computed_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("location", "date")
        ordering = ["-date"]

    def __str__(self):
        return f"{self.location.name} {self.date}: £{self.total_revenue}"
