# Generated by Django 5.2.14 on 2026-05-28 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='Rich text / markdown content')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('category', models.CharField(choices=[('daily_briefing', 'Daily Briefing'), ('policy_update', 'Policy Update'), ('equipment', 'Equipment'), ('menu_change', 'Menu Change'), ('health_safety', 'Health & Safety'), ('general', 'General')], default='general', max_length=30)),
                ('is_pinned', models.BooleanField(default=False, help_text='Sticky at top of feed')),
                ('requires_acknowledgement', models.BooleanField(default=False, help_text="If true, staff must confirm they've read this")),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Empty = all roles. Or list of role slugs.')),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file URLs/paths attached to this memo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_memos', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Null = org-wide memo visible at all locations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='core.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='core.organisation')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='memos.memo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='memos.memo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('memo', 'user')},
            },
        ),
    ]
