# Generated by Django 5.2.14 on 2026-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text="Empty = all roles. Or list of role slugs, e.g. ['staff', 'content_manager']"),
        ),
    ]
