# Generated by Django 5.2.14 on 2026-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict, help_text='\n        Permission flags. Example:\n        {\n            "memos": {"create": true, "read": true, "update": true, "delete": true, "acknowledge": true},\n            "inventory": {"create": true, "read": true, "update": true, "stock_take": true},\n            "waste": {"create": true, "read": true, "view_reports": true},\n            "datechecks": {"create": true, "read": true, "resolve_alerts": true, "manage_schedule": true},\n            "sales": {"view_dashboard": true, "view_financials": true, "export": true},\n            "users": {"invite": true, "manage": true, "view": true},\n            "settings": {"manage_location": true, "manage_org": true}\n        }\n        '),
        ),
    ]
