# Generated by Django 5.2.14 on 2026-05-28 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('menu_item', 'Menu Item'), ('stock_item', 'Stock Item')], max_length=20)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(max_length=20)),
                ('reason', models.CharField(choices=[('over_production', 'Over-production / Over-prepped'), ('expired', 'Expired / Past Use-by'), ('customer_return', 'Customer Return / Remake'), ('dropped_spillage', 'Dropped / Spillage'), ('equipment_failure', 'Equipment Failure'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], max_length=30)),
                ('reason_note', models.TextField(blank=True, help_text="Free-text detail, especially if reason is 'Other'")),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Calculated from item cost × quantity', max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_photos/')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_entries', to='core.location')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_entries', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_entries', to='sales.menuitem')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_entries', to='inventory.stockitem')),
            ],
            options={
                'verbose_name_plural': 'waste entries',
                'ordering': ['-logged_at'],
            },
        ),
    ]
