# Generated by Django 5.2.14 on 2026-05-28 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('coffee_tea', 'Coffee & Tea'), ('dry_goods', 'Dry Goods'), ('fresh_produce', 'Fresh Produce'), ('bakery', 'Bakery'), ('meat_fish', 'Meat & Fish'), ('beverages', 'Beverages'), ('packaging', 'Packaging'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=30)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litres'), ('ml', 'Millilitres'), ('units', 'Units'), ('boxes', 'Boxes'), ('bags', 'Bags')], default='units', max_length=10)),
                ('preferred_suppliers', models.JSONField(blank=True, default=list, help_text='List of supplier names/contacts for this item')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('conducted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-conducted_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_quantity', models.FloatField(blank=True, help_text='What the system thought we had (snapshot at count time)', null=True)),
                ('variance', models.FloatField(blank=True, help_text='counted - expected (positive = surplus, negative = shrinkage)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('par_level', models.FloatField(default=0, help_text='Minimum quantity before triggering a low-stock alert', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit in GBP', max_digits=10)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('delivery', 'Delivery Received'), ('waste', 'Waste Deduction'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('correction', 'Manual Correction'), ('sale_deduction', 'Sale Deduction')], max_length=20)),
                ('quantity_change', models.FloatField(help_text='Positive = stock in, negative = stock out')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.location')),
                ('related_location', models.ForeignKey(blank=True, help_text='For transfers: the other location involved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_adjustments', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
