# Generated by Django 5.2.14 on 2026-05-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='related_waste_entry',
            field=models.ForeignKey(blank=True, help_text='Auto-linked when waste is logged', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.wasteentry'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='locationstock',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='core.location'),
        ),
        migrations.AddField(
            model_name='stocktakeentry',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_entries', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stocktakeentry',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.stocktake'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('organisation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together={('stock_item', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeentry',
            unique_together={('stock_take', 'stock_item')},
        ),
    ]
