# Generated by Django 5.2.14 on 2026-05-28 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('memo_created', 'Memo Created'), ('memo_updated', 'Memo Updated'), ('memo_deleted', 'Memo Deleted'), ('memo_acknowledged', 'Memo Acknowledged'), ('stock_take', 'Stock Take Completed'), ('stock_adjusted', 'Stock Adjusted'), ('stock_transfer', 'Stock Transferred'), ('waste_logged', 'Waste Logged'), ('user_invited', 'User Invited'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('sale_imported', 'Sales Data Imported')], max_length=30)),
                ('target_model', models.CharField(blank=True, help_text="e.g. 'Memo', 'StockItem', 'User'", max_length=100)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context for the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
