# Generated by Django 5.2.14 on 2026-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Extra context, e.g. {'old_role': 'staff', 'new_role': 'content_manager'}"),
        ),
    ]
