# Generated by Django 5.2.14 on 2026-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitylog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('memo_created', 'Memo Created'), ('memo_updated', 'Memo Updated'), ('memo_deleted', 'Memo Deleted'), ('memo_acknowledged', 'Memo Acknowledged'), ('stock_take', 'Stock Take Completed'), ('stock_adjusted', 'Stock Adjusted'), ('stock_transfer', 'Stock Transferred'), ('waste_logged', 'Waste Logged'), ('user_invited', 'User Invited'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('sale_imported', 'Sales Data Imported'), ('date_check_started', 'Date Check Started'), ('date_check_completed', 'Date Check Completed'), ('expiry_alert_resolved', 'Expiry Alert Resolved')], max_length=30),
        ),
    ]
