# Generated by Django 5.2.14 on 2026-05-28 17:07

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_role_permissions'),
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="General notes about this check round, e.g. 'Fridge 2 was not checked — broken seal'")),
                ('items_checked', models.PositiveIntegerField(default=0, help_text='Total items checked in this round')),
                ('items_expired', models.PositiveIntegerField(default=0, help_text='Items found already expired')),
                ('items_expiring_soon', models.PositiveIntegerField(default=0, help_text='Items expiring within the alert threshold')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_checks', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_checks', to='core.location')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DateCheckEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Denormalised product name for display, or custom name if not in stock/menu', max_length=200)),
                ('earliest_expiry', models.DateField(help_text='The earliest use-by or best-before date found on this product')),
                ('quantity_at_risk', models.FloatField(default=1, help_text='How many units have this expiry date', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='units', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost value of the at-risk stock', max_digits=10)),
                ('expiry_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Expiring Soon'), ('critical', 'Expires Today/Tomorrow'), ('expired', 'Expired')], default='ok', max_length=20)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('use_first', 'Use First (FIFO)'), ('reduce_price', 'Reduce Price'), ('dispose', 'Dispose'), ('disposed', 'Disposed')], default='none', max_length=20)),
                ('action_note', models.TextField(blank=True, help_text="Notes about action taken, e.g. 'Moved to front of display'")),
                ('photo', models.ImageField(blank=True, help_text='Photo of the date label for audit trail', null=True, upload_to='date_check_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='datechecks.datecheck')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_check_entries', to='sales.menuitem')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_check_entries', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['earliest_expiry'],
            },
        ),
        migrations.CreateModel(
            name='DateCheckSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every Other Day'), ('twice_weekly', 'Twice Weekly'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('alert_threshold_days', models.PositiveIntegerField(default=3, help_text='Products expiring within this many days trigger a WARNING alert')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Send a reminder if no date check has been done today')),
                ('reminder_time', models.TimeField(default=datetime.time(9, 0), help_text='Time to send the reminder if check is overdue')),
                ('last_check_at', models.DateTimeField(blank=True, help_text='Auto-updated when a date check is completed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_check_schedule', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('quantity_at_risk', models.FloatField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alert_level', models.CharField(choices=[('warning', 'Warning — Expiring Soon'), ('critical', 'Critical — Expires Today/Tomorrow'), ('expired', 'Expired — Dispose Immediately')], max_length=20)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used Before Expiry'), ('disposed', 'Disposed'), ('wasted', 'Logged as Waste'), ('rechecked', 'Re-checked — Date Updated'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_check_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='datechecks.datecheckentry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='core.location')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('waste_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_alerts', to='waste.wasteentry')),
            ],
            options={
                'ordering': ['expiry_date', '-alert_level'],
            },
        ),
    ]
