# Generated by Django 5.2.14 on 2026-05-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text="Overview of what this training covers and who it's for")),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('food_safety', 'Food Safety'), ('barista', 'Barista Skills'), ('equipment', 'Equipment'), ('customer_service', 'Customer Service'), ('health_safety', 'Health & Safety'), ('closing', 'Closing Procedures'), ('opening', 'Opening Procedures'), ('other', 'Other')], default='other', max_length=30)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image shown in the training library', null=True, upload_to='training/covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to complete all steps, in minutes')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, all staff at assigned locations must complete this')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="Which roles should complete this. Empty = all roles. E.g. ['staff', 'content_manager']")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programmes', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(blank=True, help_text='Locations where this programme is active. Empty = all locations.', related_name='training_programmes', to='core.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programmes', to='core.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='The step the user is currently on')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrolments', to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrolments', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='training.trainingprogramme')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('programme', 'user', 'location')},
            },
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1, help_text='Position in the timeline. Steps are displayed in ascending order.')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Detailed instructions, key points, tips. Supports markdown.')),
                ('image', models.ImageField(blank=True, help_text='Visual aid — photo of equipment, diagram, screenshot, etc.', null=True, upload_to='training/steps/')),
                ('video_url', models.URLField(blank=True, help_text='Optional link to an external video (YouTube, Vimeo, etc.)')),
                ('requires_acknowledgement', models.BooleanField(default=False, help_text='If true, staff must confirm understanding before proceeding')),
                ('tips', models.TextField(blank=True, help_text='Additional tips or common mistakes to avoid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='training.trainingprogramme')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('programme', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TrainingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_comments', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='training.trainingprogramme')),
                ('step', models.ForeignKey(blank=True, help_text='If set, this comment is about a specific step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='training.trainingstep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged', models.BooleanField(default=False, help_text='True if the user confirmed understanding (for steps that require it)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the user, e.g. questions or feedback')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='training.trainingenrolment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.trainingstep')),
            ],
            options={
                'ordering': ['step__order'],
                'unique_together': {('enrolment', 'step')},
            },
        ),
    ]
