# Generated by Django 5.2.14 on 2026-05-28 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hot_drinks', 'Hot Drinks'), ('cold_drinks', 'Cold Drinks'), ('food', 'Food'), ('bakery', 'Bakery'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost to make this item', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.organisation')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(blank=True, help_text='External reference from POS system', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('mobile', 'Mobile Payment'), ('other', 'Other')], default='card', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='sales.menuitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('average_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('top_items', models.JSONField(blank=True, default=list, help_text="[{'item_id': ..., 'name': ..., 'qty': ..., 'revenue': ...}, ...]")),
                ('hourly_breakdown', models.JSONField(blank=True, default=dict, help_text="{'07': {'revenue': 120.50, 'transactions': 14}, ...}")),
                ('category_breakdown', models.JSONField(blank=True, default=dict, help_text="{'hot_drinks': {'revenue': ..., 'qty': ...}, ...}")),
                ('waste_total', models.DecimalField(decimal_places=2, default=0, help_text='Total waste cost for the day', max_digits=10)),
                ('waste_percentage', models.FloatField(default=0, help_text='waste_total / total_revenue × 100')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.location')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
